development:
  adapter: postgresql
  encoding: unicode
  database: waterfall_development
  pool: 5
  username: dev
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: waterfall_test
  pool: 5
  username: dev
  password: