require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StylesheetsController do

  # This should return the minimal set of attributes required to create a valid
  # Stylesheet. As you add validations to Stylesheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "account_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StylesheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stylesheets as @stylesheets" do
      stylesheet = Stylesheet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stylesheets).should eq([stylesheet])
    end
  end

  describe "GET show" do
    it "assigns the requested stylesheet as @stylesheet" do
      stylesheet = Stylesheet.create! valid_attributes
      get :show, {:id => stylesheet.to_param}, valid_session
      assigns(:stylesheet).should eq(stylesheet)
    end
  end

  describe "GET new" do
    it "assigns a new stylesheet as @stylesheet" do
      get :new, {}, valid_session
      assigns(:stylesheet).should be_a_new(Stylesheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested stylesheet as @stylesheet" do
      stylesheet = Stylesheet.create! valid_attributes
      get :edit, {:id => stylesheet.to_param}, valid_session
      assigns(:stylesheet).should eq(stylesheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stylesheet" do
        expect {
          post :create, {:stylesheet => valid_attributes}, valid_session
        }.to change(Stylesheet, :count).by(1)
      end

      it "assigns a newly created stylesheet as @stylesheet" do
        post :create, {:stylesheet => valid_attributes}, valid_session
        assigns(:stylesheet).should be_a(Stylesheet)
        assigns(:stylesheet).should be_persisted
      end

      it "redirects to the created stylesheet" do
        post :create, {:stylesheet => valid_attributes}, valid_session
        response.should redirect_to(Stylesheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stylesheet as @stylesheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stylesheet.any_instance.stub(:save).and_return(false)
        post :create, {:stylesheet => { "account_id" => "invalid value" }}, valid_session
        assigns(:stylesheet).should be_a_new(Stylesheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stylesheet.any_instance.stub(:save).and_return(false)
        post :create, {:stylesheet => { "account_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stylesheet" do
        stylesheet = Stylesheet.create! valid_attributes
        # Assuming there are no other stylesheets in the database, this
        # specifies that the Stylesheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stylesheet.any_instance.should_receive(:update).with({ "account_id" => "1" })
        put :update, {:id => stylesheet.to_param, :stylesheet => { "account_id" => "1" }}, valid_session
      end

      it "assigns the requested stylesheet as @stylesheet" do
        stylesheet = Stylesheet.create! valid_attributes
        put :update, {:id => stylesheet.to_param, :stylesheet => valid_attributes}, valid_session
        assigns(:stylesheet).should eq(stylesheet)
      end

      it "redirects to the stylesheet" do
        stylesheet = Stylesheet.create! valid_attributes
        put :update, {:id => stylesheet.to_param, :stylesheet => valid_attributes}, valid_session
        response.should redirect_to(stylesheet)
      end
    end

    describe "with invalid params" do
      it "assigns the stylesheet as @stylesheet" do
        stylesheet = Stylesheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stylesheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => stylesheet.to_param, :stylesheet => { "account_id" => "invalid value" }}, valid_session
        assigns(:stylesheet).should eq(stylesheet)
      end

      it "re-renders the 'edit' template" do
        stylesheet = Stylesheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stylesheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => stylesheet.to_param, :stylesheet => { "account_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stylesheet" do
      stylesheet = Stylesheet.create! valid_attributes
      expect {
        delete :destroy, {:id => stylesheet.to_param}, valid_session
      }.to change(Stylesheet, :count).by(-1)
    end

    it "redirects to the stylesheets list" do
      stylesheet = Stylesheet.create! valid_attributes
      delete :destroy, {:id => stylesheet.to_param}, valid_session
      response.should redirect_to(stylesheets_url)
    end
  end

end
